baseURL = "https://leftaxe.com/"
languageCode = "en-us"
title = "Gilbert F. Sewovoe-Ekoue"

theme = "minimo"
enableemoji = "true"
disqusShortname = ""
googleAnalytics = ""

Paginate = 20

preserveTaxonomyNames = true

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodeFences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

enableRobotsTXT = true # generate robots.txt

[taxonomies]
category = "categories"
tag = "tags"

[author]
name = "Gilbert F. Sewovoe-Ekoue"

[params.info]
description = "Software Engineer & Bricoleur"
title404 = "Whoops! Nothing here."

[params.settings]
name = "Gilbert F. Sewovoe-Ekoue"
description = "Software Engineer & Bricoleur"
dateFormat = "2006, Jan 2"
copyrightOwner = "Gilbert F. Sewovoe-Ekoue"
copyrightStartYear = "2017"
hideEntryNavigation = ["page"] # boolean / array of sections
recentPostsLength = 4
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false
googleAnalyticsUserID=""

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.seo]
titleSeparator = "-"

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username


[params.social.config]
platforms = ["github", "linkedin"]

[params.social]
# email = "gilberts55@gmail.com"
github = "gilbertek"
twitter = "gilbertek"
linkedin = "gilbertekoue"
codepen = ""
facebook = ""
instagram = ""

[params.copyright]
prefix = ""
holder = "Gilbert Sewovoe-Ekoue"
suffix = ""

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true
plainIDAnchors = true

[languages]
[languages.en]
lang = "en"
languageName = "English"
weight = 1

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3
