baseURL = "https://leftaxe.com/"
languageCode = "en-us"
title = "Gilbert F. Sewovoe-Ekoue"

theme = "minimo"
enableemoji = "true"
disqusShortname = ""
googleAnalytics = "UA-133296755-1"

Paginate = 10
preserveTaxonomyNames = true

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodeFences = true

enableGitInfo = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

enableRobotsTXT = true # generate robots.txt

[taxonomies]
  category = "categories"
  tag = "tags"

[author]
  name = "Gilbert F. Sewovoe-Ekoue"

[params.info]
  description = "Hacker. Builder. Leader."
  title404 = "Whoops! Nothing here."

[params.settings]
  name = "Gilbert F. Sewovoe-Ekoue"
  description = "Software Engineer & Bricoleur"
  dateFormat = "2006, Jan 2"
  copyrightOwner = "Gilbert F. Sewovoe-Ekoue"
  copyrightStartYear = "2017"
  hideEntryNavigation = ["page"] # boolean / array of sections
  recentPostsLength = 4
  hideSocialMenu = false
  showReadingTime = true
  noTermCloudShuffle = false
  showLastmod = true

[params.widgets]
  homepage = ["recent_posts"]
  footer = ["social_menu"]

[params.assets]
  favicon = "favicon.ico"
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]
  gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.seo]
  titleSeparator = "-"

[params.social.config]
  platforms = ["github", "linkedin", "twitter"]

[params.social]
  # email = "gilberts55@gmail.com"
  github = "gilbertek"
  twitter = "gilbertek"
  linkedin = "gilbertekoue"
  codepen = ""

[params.copyright]
  prefix = ""
  holder = "Gilbert Sewovoe-Ekoue"
  suffix = ""

[permalinks]
  page = "/:slug/"

[blackfriday]
  hrefTargetBlank = true

[languages]

[languages.en]
  weight = 1
  lang = "en"
  languageName = "English"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3
